sudo: false
cache:
  directories:
  - "$HOME/.stack"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
script:
- stack --no-terminal --skip-ghc-check test
env:
  global:
  - secure: lMVWRVzRUVsbxp1Zce9ezxCRaaFR/+UVpbWT+ElvTQz+1kSs1CccGdMdocKD2edY2mt0hhXDe3jpaZMnW7sTBkrivg76MdAb2UyZDjzj0xXUpcbUB1pweaFGWxE9HkpIq+fb0NkajWgw1wpZqk/+vjU/8RMPBvDkvIHQRtYewY1nnPDpDPP4nUqnKNdPOlDKRsHY66l+XN6ukxXFCqb0PBl4qmzzgbwHpLxNBPgACtPcd4m7wVLVyl1tdiektWhblO4gXME0B8Qm9Ggq1Bbjj0FOqX/rHSalzOpOBeMK8b1hxHehFSkr+Zjqwn34c7IMAZ5zjuOG7vUeHR6iIjtgDSBEPCMsWze/4vb6JGl679LISZ3IQuabBf7sJGfyuCzVLQviCqqDMdzWDPPHNkUmeBGqQUW+awwZBygUTj3dMH2AFDtq1iN0crgxtP9m+awVb+dGpiMfV3iWefiO7ADVvz1Bs+pkmHfJWD0nRDm2rtOw/iRimVnFtfa6QYr53uYnNKTYkqGT65ca4m87+lIwWqU0z5184KTSqHiebZE7/qTZovcwKymM0lW6YdOeMI+O252DbOowaTDIcpNIoDEjtueIfgNhi1T79Es8m8MFvtRWqPCHLm3aTVQwsT0LWR7DAGA95URFG6Cbz811IMWzC2L1cGcT7ELdcmXpTDm7zlg=
  - secure: p4LgpIgqOy5LVThcvotfTqPCDXti8QnlJT7f+EVMogzP8pZXaxT/zBy1iBaRgVVUg7GaDFAOly4LhFDOJHVdsMeXWWZW7zw8awxvzrQr48mS+LeOTjgZs5o9mAcRxc28YzRElWen0yrIXCMb2h8Pn/eJrhijS4xq30AsBlp/tT1QvARicz+VMk2bFiei+9RL3F/TbSPH8rHhUPSE4rS90rioELfErwZ50H4z95khhbd/TH8P8t05F5OXQtKIyaCz9uBIk1R9NDYFLtREjtslldYlOrbml5i7rwJEAnGSp/HeXXy59YUBS32iZVvgLELeTLonVFHIcAU6lBuYG2dScoQolBi0h3MY1u0RORO1ZnNgKfIbhFpRL44I+vRZFyJPIAy/ojcGy6UOpuVieWjCDshWqlTBNM6F70sLMZ4KJcb05Pig55bEP1Ya3A4GlAbzAuVrPTFKQLwNtILDpCDlYsZ1nHtL/pgbKdHK01x8FdFTnb4WWpa+yRweSZRbABctrNl7pDJwC12eFIzT+a06RusspmAqUVdWA/RrdxHyIVmaCGutK3eMbOHhGpczRIddfG/RLogGr5nyfcmcSWB6WRbvdfNtvrssc97I0MvVtn2fY58O2FuvzHiUZJs4831WWHez/5/n0670ZZvWFUYu01VvUThk/rgP/n6i/G1sVY0=
